texto = "Prueba dos dos"
print("Upper")
print(texto.upper())
print("Lower")
print(texto.lower())
print("Capitalize")
print(texto.capitalize())
print("Count")
#print(texto.count())
print("Fing")
#print(texto.fing())
print("Isdigit")
print(texto.isdigit())
print("Isalnum")
print(texto.isalnum ())
print("Isalpha")
print(texto.isalpha())
print("Split")
print(texto.split())
print("Strip")
print(texto.strip())
print("Replace")
print(texto.replace(" ","-"))
print("Rfind")
print(texto.rfind("o"))
print("Len")
print(len(texto))